### ISSUE TITLE
*Request* - Changing the Set output format.

### ISSUE THREAD

**Issue by SystemAnonymous** [token03/clodsire-bot#1]
Hey, so currently when you request a /set. Example /set Charizard
When you copy the format it provides, this is what it produces.

Item: Heavy-Duty Boots
Moves:
-Roost        -Flamethrower 
-Hurricane    -Toxic        
Nature: Timid
Evs:
  spa: 252
  spd: 4
  spe: 252

I was wondering if you can change the format to match Pokemon Showdown. Like this? =)

Charizard @ Heavy-Duty Boots  
Ability: Blaze  
Tera Type: Fire  
EVs: 252 Atk / 4 SpA / 252 Spe  
Lonely Nature  
- Dragon Dance  
- Fire Blast  
- Dragon Claw  
- Flare Blitz

Thank you, Kindest regards.

**Comment by token03** [comment]
fixed!

thanks for the suggestion.
